// <auto-generated />
namespace Entity_Framework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dsdfsf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dsdfsf));
        
        string IMigrationMetadata.Id
        {
            get { return "202404260956403_dsdfsf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
